# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/kirby/Software/Linux_Unreal_Engine_5.7.2

TARGETS = \
	DancePuppet-Android-DebugGame  \
	DancePuppet-Android-Development  \
	DancePuppet-Android-Shipping  \
	DancePuppet-Linux-DebugGame  \
	DancePuppet-Linux-Development  \
	DancePuppet-Linux-Shipping  \
	DancePuppet-LinuxArm64-DebugGame  \
	DancePuppet-LinuxArm64-Development  \
	DancePuppet-LinuxArm64-Shipping  \
	DancePuppet \
	DancePuppetEditor-Linux-DebugGame  \
	DancePuppetEditor-Linux-Development  \
	DancePuppetEditor \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend DancePuppetEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug DancePuppetEditor-Linux-Debug


DancePuppet-Android-DebugGame:
	 $(BUILD) DancePuppet Android DebugGame  -Project="/home/kirby/Documents/Unreal Projects/DancePuppet/DancePuppet.uproject" $(ARGS)

DancePuppet-Android-Development:
	 $(BUILD) DancePuppet Android Development  -Project="/home/kirby/Documents/Unreal Projects/DancePuppet/DancePuppet.uproject" $(ARGS)

DancePuppet-Android-Shipping:
	 $(BUILD) DancePuppet Android Shipping  -Project="/home/kirby/Documents/Unreal Projects/DancePuppet/DancePuppet.uproject" $(ARGS)

DancePuppet-Linux-DebugGame:
	 $(BUILD) DancePuppet Linux DebugGame  -Project="/home/kirby/Documents/Unreal Projects/DancePuppet/DancePuppet.uproject" $(ARGS)

DancePuppet-Linux-Development:
	 $(BUILD) DancePuppet Linux Development  -Project="/home/kirby/Documents/Unreal Projects/DancePuppet/DancePuppet.uproject" $(ARGS)

DancePuppet-Linux-Shipping:
	 $(BUILD) DancePuppet Linux Shipping  -Project="/home/kirby/Documents/Unreal Projects/DancePuppet/DancePuppet.uproject" $(ARGS)

DancePuppet-LinuxArm64-DebugGame:
	 $(BUILD) DancePuppet LinuxArm64 DebugGame  -Project="/home/kirby/Documents/Unreal Projects/DancePuppet/DancePuppet.uproject" $(ARGS)

DancePuppet-LinuxArm64-Development:
	 $(BUILD) DancePuppet LinuxArm64 Development  -Project="/home/kirby/Documents/Unreal Projects/DancePuppet/DancePuppet.uproject" $(ARGS)

DancePuppet-LinuxArm64-Shipping:
	 $(BUILD) DancePuppet LinuxArm64 Shipping  -Project="/home/kirby/Documents/Unreal Projects/DancePuppet/DancePuppet.uproject" $(ARGS)

DancePuppet: DancePuppet-Linux-Development

DancePuppetEditor-Linux-DebugGame:
	 $(BUILD) DancePuppetEditor Linux DebugGame  -Project="/home/kirby/Documents/Unreal Projects/DancePuppet/DancePuppet.uproject" $(ARGS)

DancePuppetEditor-Linux-Development:
	 $(BUILD) DancePuppetEditor Linux Development  -Project="/home/kirby/Documents/Unreal Projects/DancePuppet/DancePuppet.uproject" $(ARGS)

DancePuppetEditor: DancePuppetEditor-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/kirby/Documents/Unreal Projects/DancePuppet/DancePuppet.uproject" -Game 

.PHONY: $(TARGETS)
